"""
LiNeP V0.2 — Dual-Plane Protocol Python Module
==============================================

Exposes high-level pure-Python implementations of the LiNeP V0.2 Dual-Plane
Runtime Baseline:
- 80-Byte UDP Control Plane Datagrams & Router State Machine
- 32-Byte TCP Data Plane Envelopes & Serialization
- Streaming Client & Deterministic Mock Server
- Conformance Test Runner
"""

from linep.v0_2.constants import (
    LINEP_V02_MAGIC,
    LINEP_V02_UDP_MAGIC,
    LINEP_V02_VERSION_MAJOR,
    LINEP_V02_VERSION_MINOR,
    LINEP_V02_HEADER_SIZE,
    LINEP_V02_UDP_DATAGRAM_SIZE,
    RuntimeProfile,
    EnvelopeType,
    EventType,
    ControlType,
    TerminalOutcome,
    ErrorCategory,
    EmbeddingNormalization,
    EmbeddingDistanceMetric,
    ControlMessageType,
    NodeAvailability,
    NodeHealth,
    NodeLifecycle,
    SessionBindingState,
    LINEP_V02_SESSION_BIND_PAYLOAD_SIZE,
    LINEP_V02_FLAG_AUTHENTICATED,
    LINEP_V02_AUTH_EXTENSION_SIZE,
    LINEP_V02_MAX_REGISTRATION_BYTES,
    LINEP_V02_MAX_VISION_IMAGE_BYTES,
    LINEP_V02_MAX_VISION_DETECTIONS,
    MessageDirection,
    RegistrationOperation,
    VisionTask,
)
from linep.v0_2.vision import (
    LABEL_SET_COCO80_V1,
    LABEL_SET_WIDERFACE_V1,
    LABEL_SET_VOC20_V1,
    VisionBox2D,
    VisionDetection,
    VisionDetectResult,
    VisionResultPayload,
    VisionModelDescriptor,
    resolve_standard_label,
    is_valid_label_for_class,
)
from linep.v0_2.envelopes import (
    StreamIdentity,
    WireEnvelopeHeader,
    ChatMessage,
    StructuredChatPayload,
    RequestEnvelope,
    GenerationOptions,
    EventEnvelope,
    ControlEnvelope,
    CapabilitiesEnvelope,
    CapabilitiesDescriptor,
    EmbeddingSpaceDescriptor,
    EmbeddingPayload,
    RuntimeErrorPayload,
    SessionBindEnvelope,
    RegistrationExtension,
    RuntimeRegistrationEnvelope,
    AuthExtension,
    encode_header,
    decode_header,
    peek_envelope_type,
    encode_request,
    decode_request,
    encode_event,
    decode_event,
    encode_control,
    decode_control,
    encode_capabilities,
    decode_capabilities,
    encode_session_bind,
    decode_session_bind,
    encode_runtime_registration,
    decode_runtime_registration,
    compute_sl1_mac,
    sign_envelope,
    verify_envelope,
)
from linep.v0_2.control_plane import (
    UdpControlDatagram,
    NodeEndpointIdentity,
    ControlPlaneNodeState,
    ControlPlaneRouter,
    encode_control_datagram,
    decode_control_datagram,
    calc_crc32,
)
from linep.v0_2.client import LiNePClient
from linep.v0_2.server import LiNePMockServer, MockServerConfig
from linep.v0_2.conformance import (
    ConformanceRunner,
    ConformanceReport,
    TestResult,
    ProfileConformanceStatus,
)

__all__ = [
    # Constants & Enums
    "LINEP_V02_MAGIC",
    "LINEP_V02_UDP_MAGIC",
    "LINEP_V02_VERSION_MAJOR",
    "LINEP_V02_VERSION_MINOR",
    "LINEP_V02_HEADER_SIZE",
    "LINEP_V02_UDP_DATAGRAM_SIZE",
    "RuntimeProfile",
    "EnvelopeType",
    "EventType",
    "ControlType",
    "TerminalOutcome",
    "ErrorCategory",
    "EmbeddingNormalization",
    "EmbeddingDistanceMetric",
    "ControlMessageType",
    "NodeAvailability",
    "NodeHealth",
    "NodeLifecycle",
    "SessionBindingState",
    "LINEP_V02_SESSION_BIND_PAYLOAD_SIZE",
    "LINEP_V02_FLAG_AUTHENTICATED",
    "LINEP_V02_AUTH_EXTENSION_SIZE",
    "LINEP_V02_MAX_REGISTRATION_BYTES",
    "MessageDirection",
    "RegistrationOperation",
    # Envelopes
    "StreamIdentity",
    "WireEnvelopeHeader",
    "ChatMessage",
    "StructuredChatPayload",
    "RequestEnvelope",
    "GenerationOptions",
    "EventEnvelope",
    "ControlEnvelope",
    "CapabilitiesEnvelope",
    "CapabilitiesDescriptor",
    "EmbeddingSpaceDescriptor",
    "EmbeddingPayload",
    "RuntimeErrorPayload",
    "SessionBindEnvelope",
    "RegistrationExtension",
    "RuntimeRegistrationEnvelope",
    "AuthExtension",
    "encode_header",
    "decode_header",
    "peek_envelope_type",
    "encode_request",
    "decode_request",
    "encode_event",
    "decode_event",
    "encode_control",
    "decode_control",
    "encode_capabilities",
    "decode_capabilities",
    "encode_session_bind",
    "decode_session_bind",
    "encode_runtime_registration",
    "decode_runtime_registration",
    "compute_sl1_mac",
    "sign_envelope",
    "verify_envelope",
    # Control Plane
    "UdpControlDatagram",
    "NodeEndpointIdentity",
    "ControlPlaneNodeState",
    "ControlPlaneRouter",
    "encode_control_datagram",
    "decode_control_datagram",
    "calc_crc32",
    # Client & Server
    "LiNePClient",
    "LiNePMockServer",
    "MockServerConfig",
    # Conformance
    "ConformanceRunner",
    "ConformanceReport",
    "TestResult",
    "ProfileConformanceStatus",
    # Vision Profile (Phase 1)
    "VisionTask",
    "LABEL_SET_COCO80_V1",
    "LABEL_SET_WIDERFACE_V1",
    "LABEL_SET_VOC20_V1",
    "VisionBox2D",
    "VisionDetection",
    "VisionDetectResult",
    "VisionResultPayload",
    "VisionModelDescriptor",
    "resolve_standard_label",
    "is_valid_label_for_class",
    "LINEP_V02_MAX_VISION_IMAGE_BYTES",
    "LINEP_V02_MAX_VISION_DETECTIONS",
]
